### ISSUE TITLE
sqlparse does not differentiate between wildcard '*' and operator '*'

### ISSUE THREAD

**Issue by adrpar** [andialbrecht/sqlparse#104]
sqlparse should differentiate between wildcard '*' such as in

select * from foo
select foo.* from foo

and operator '*' such as in

select 2.0*count(bar) from foo

**Comment by vmuriart** [comment]
commit https://github.com/andialbrecht/sqlparse/pull/235/commits/1e770d9b99983fa82375b71c5b3f5d8c6bb1a72e address and fixes this.

Issue can be closed.

**Comment by vmuriart** [comment]
One note to add is that multiplication distinction only happens when grouping is applied.
Without grouping there isn't any context for this to be resolved. 

Perhaps a solution to this is to leave `grouping` on by default in order to be able to resolve context.
Then again, the only time grouping is disabled is when `split` is used to split statements.

**Comment by andialbrecht** [comment]
split is intended to work as fast as possible. I don't think that we need
this context without grouping at all.

Vik <notifications@github.com> schrieb am So., 12. Juni 2016 um 22:01 Uhr:

**Comment by vmuriart** [comment]
Yup. Upon inspection I realizing split wouldn't benefit from the
grouping/multiplication so left it alone
