### ISSUE TITLE
sqlparse not recognizing two statements

### ISSUE THREAD

**Issue by swathiiyer2** [andialbrecht/sqlparse#430]
While trying to parse these queries together, sqlparse does not recognize them as two separate statements - 

```sql
SELECT a.date, b.name FROM
telemetry_core_parquet a
JOIN right_table b
ON a.date = CAST((b.year * 10000 + b.month * 100 + b.day) as VARCHAR)

SELECT a.date, b.name FROM
left_table a
JOIN (
  SELECT
    CAST((b.year * 10000 + b.month * 100 + b.day) as VARCHAR) date,  # generate join key
    name
  FROM right_table
) b
ON a.date = b.date  # Simple equi-join
```

**Comment by andialbrecht** [comment]
Hi @swathiiyer2, this behavior is the intended behavior. There's no semicolon between both statements, so the parser has no chance to detect two statements. sqlparse as a non-validating SQL parsers needs the semicolon there, other validating SQL parsers would see an error since it's syntactically incorrect.
