### ISSUE TITLE
Non-ASCII characters cause an error

### ISSUE THREAD

**Issue by prettydiff** [andialbrecht/sqlparse#462]
Non-ASCII characters break sqlformat:  https://github.com/Glavin001/atom-beautify/issues/2298

**Comment by andialbrecht** [comment]
I'm pretty sure that this isn't an issue related to sqlparse, but how it is called from atom-beautify. Here's an example session:

>>> sql = """SELECT id,
...        name AS `Название`
... FROM shop_products"""
>>> import sqlparse
>>> print(sqlparse.format(sql, reindent=True))
SELECT id,
       name AS `Название`
FROM shop_products
>>>

Similar encoding issues came up earlier with third-party software implemented in Node.js. Seems like that the problem is somehow related on how the original query is passed to the Python subprocess for formatting.
