### ISSUE TITLE
sqlformat --reindent not Unicode ready

### ISSUE THREAD

**Issue by jidanni** [andialbrecht/sqlparse#641]
```
$ cat e.sql 
SELECT a, b, c, d FROM t;
SELECT a, b, 業者名稱, d FROM t;
$ sqlformat --reindent e.sql
SELECT a,
       b,
       c,
       d
FROM t;


SELECT a,
       b, 業者名稱, d
FROM t;
```

**Comment by andialbrecht** [comment]
Quick analysis of the issue: The regex that should match is the fallback regex that checks for keywords, `'[0-9_A-ZÀ-Ü][_$#\w]*'`. This is the regex that also identifies `a` as a (column) name since the default return value of `is_keyword` is `tokens.Name`. 

It's funny that we allow `À-Ü` here and not only ASCII letters, digits and underscore in the beginning of a name. That was introduced 5 years ago in 617d38908bb999018598e3cbbdd123a992a08ba9. In consequence we should allow any unicode character. 

A workaround for the parser is to put it in square brackets `[業者名稱]`.

@jidanni out of curiosity, which database system are you using?

**Comment by jidanni** [comment]
sqlite3.

**Comment by andialbrecht** [comment]
Thanks for reporting!
